#!/usr/bin/env python3
"""Generate vision ML model weights for hive state classification (8->24->16->5)."""

import numpy as np

rng = np.random.default_rng(42)
N_PER_CLASS = 2000

def make_normal(n):
    bc=rng.uniform(2,15,n); mot=rng.uniform(5,25,n); col=rng.uniform(10,40,n)
    act=rng.uniform(5,25,n); sz=rng.uniform(40,200,n); tr=rng.uniform(-3,5,n)
    atr=rng.uniform(-10,10,n); mtr=rng.uniform(-10,10,n)
    return np.column_stack([bc/100,mot/100,col/100,act/100,sz/600,tr/20,atr/100,mtr/100])

def make_high_activity(n):
    bc=rng.uniform(15,30,n); mot=rng.uniform(20,45,n); col=rng.uniform(20,50,n)
    act=rng.uniform(25,50,n); sz=rng.uniform(60,300,n); tr=rng.uniform(0,10,n)
    atr=rng.uniform(5,25,n); mtr=rng.uniform(5,20,n)
    return np.column_stack([bc/100,mot/100,col/100,act/100,sz/600,tr/20,atr/100,mtr/100])

def make_swarming(n):
    bc=rng.uniform(30,80,n); mot=rng.uniform(40,80,n); col=rng.uniform(30,70,n)
    act=rng.uniform(50,95,n); sz=rng.uniform(80,500,n); tr=rng.uniform(5,30,n)
    atr=rng.uniform(20,60,n); mtr=rng.uniform(10,40,n)
    return np.column_stack([bc/100,mot/100,col/100,act/100,sz/600,tr/20,atr/100,mtr/100])

def make_low_activity(n):
    bc=rng.uniform(0,3,n); mot=rng.uniform(0,8,n); col=rng.uniform(0,15,n)
    act=rng.uniform(0,8,n); sz=rng.uniform(10,80,n); tr=rng.uniform(-5,0,n)
    atr=rng.uniform(-15,0,n); mtr=rng.uniform(-10,0,n)
    return np.column_stack([bc/100,mot/100,col/100,act/100,sz/600,tr/20,atr/100,mtr/100])

def make_disturbed(n):
    bc=rng.uniform(0,10,n); mot=rng.uniform(50,100,n); col=rng.uniform(5,30,n)
    act=rng.uniform(5,40,n); sz=rng.uniform(20,150,n); tr=rng.uniform(-10,10,n)
    atr=rng.uniform(-20,20,n); mtr=rng.uniform(20,80,n)
    return np.column_stack([bc/100,mot/100,col/100,act/100,sz/600,tr/20,atr/100,mtr/100])

def generate_all():
    X = np.vstack([make_normal(N_PER_CLASS), make_high_activity(N_PER_CLASS),
                   make_swarming(N_PER_CLASS), make_low_activity(N_PER_CLASS),
                   make_disturbed(N_PER_CLASS)])
    y = np.hstack([np.full(N_PER_CLASS, i) for i in range(5)])
    idx = rng.permutation(len(X))
    return X[idx], y[idx]

def softmax(x): e = np.exp(x - x.max(axis=-1, keepdims=True)); return e / e.sum(axis=-1, keepdims=True)
def relu(x): return np.maximum(x, 0.0)
def relu_deriv(x): return (x > 0).astype(np.float64)
def acc(p, y): return (p.argmax(axis=-1) == y).mean()

def train():
    X, y = generate_all()
    n = len(X); split = int(n * 0.8)
    X_train, y_train = X[:split], y[:split]
    X_test,  y_test  = X[split:], y[split:]

    mean = X_train.mean(axis=0); std = X_train.std(axis=0) + 1e-8
    X_train = (X_train - mean) / std; X_test = (X_test - mean) / std

    I, H1, H2, O = 8, 24, 16, 5
    def init(fin, fout): return rng.normal(0, np.sqrt(2.0/fin), (fin, fout)).astype(np.float64)
    W1, b1 = init(I, H1), np.zeros(H1, np.float64)
    W2, b2 = init(H1, H2), np.zeros(H2, np.float64)
    W3, b3 = init(H2, O), np.zeros(O, np.float64)

    lr = 0.01
    for ep in range(200):
        idx = rng.permutation(split)
        total_loss = 0; batches = 0
        for s in range(0, split, 64):
            bx = X_train[idx[s:s+64]]; by = y_train[idx[s:s+64]]; bs = len(bx)
            z1 = bx@W1+b1; a1=relu(z1); z2=a1@W2+b2; a2=relu(z2); z3=a2@W3+b3; a3=softmax(z3)
            total_loss += -np.log(a3[np.arange(bs), by]+1e-10).mean(); batches += 1
            dz3=a3.copy(); dz3[np.arange(bs), by]-=1; dz3/=bs
            dW3=a2.T@dz3; db3=dz3.sum(0); da2=dz3@W3.T; dz2=da2*relu_deriv(z2)
            dW2=a1.T@dz2; db2=dz2.sum(0); da1=dz2@W2.T; dz1=da1*relu_deriv(z1)
            dW1=bx.T@dz1; db1=dz1.sum(0)
            for w,dw in [(W1,dW1),(W2,dW2),(W3,dW3)]: w-=lr*dw
            for b,db in [(b1,db1),(b2,db2),(b3,db3)]: b-=lr*db
        if ep%40==0 or ep==199:
            ta=acc(softmax(relu(relu(X_train@W1+b1)@W2+b2)@W3+b3), y_train)
            te=acc(softmax(relu(relu(X_test@W1+b1)@W2+b2)@W3+b3), y_test)
            print(f"Epoch {ep:3d}: loss={total_loss/batches:.4f}  train_acc={ta:.3f}  test_acc={te:.3f}")

    export(W1,b1,W2,b2,W3,b3,mean,std)
    print(f"Model exported: vision_model_data.h (701 params, test_acc={te:.3f})")

FMT = "{:.8e}f"
def export(W1,b1,W2,b2,W3,b3,mean,std):
    lines = ["/* Auto-generated by train_vision_model.py -- DO NOT EDIT */","",
             "#ifndef VISION_MODEL_DATA_H","#define VISION_MODEL_DATA_H","",
             "static const int vision_layer_dims[4] = {8, 24, 16, 5};",""]
    for idx,(W,B) in enumerate([(W1,b1),(W2,b2),(W3,b3)]):
        wf = W.astype(np.float32).flatten(); bf = B.astype(np.float32).flatten()
        for name,arr in [(f"vision_w{idx}",wf),(f"vision_b{idx}",bf)]:
            lines.append(f"static const float {name}[{len(arr)}] = {{")
            for j in range(0, len(arr), 8):
                lines.append("    " + ", ".join(FMT.format(x) for x in arr[j:j+8]) + ",")
            lines.append("};"); lines.append("")
    lines.append("static const float *vision_weights[3] = {vision_w0, vision_w1, vision_w2};")
    lines.append("static const float *vision_biases[3]  = {vision_b0, vision_b1, vision_b2};")
    lines.append('static const char  vision_activations[] = "rrs";'); lines.append("")
    lines.append(f"static const float vision_input_mean[8] = {{{','.join(FMT.format(x) for x in mean.astype(np.float32))}}};")
    lines.append(f"static const float vision_input_std[8]  = {{{','.join(FMT.format(x) for x in std.astype(np.float32))}}};")
    lines.append(""); lines.append("#endif /* VISION_MODEL_DATA_H */")
    dest = __file__.replace("tools\\training\\","src\\").replace("tools/training/","src/").replace("train_vision_model.py","vision_model_data.h")
    open(dest,"w").write("\n".join(lines)+"\n")

if __name__ == "__main__":
    train()
